config/routes.rb
Rails.application.routes.draw do
    root 'sessions#new'
    
    get 'home/index'
    resource :registration
    resource :session
    resource :password_reset
    resource :password
    resources :students

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
	attribute :teacher  #for store teacher in variable for processing the request so it will automatically cleared on new request
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
	has_secure_password

	validates :name, presence: true
	validates :email, presence: true, uniqueness: true
	normalizes :email, with: ->(email) {email.strip.downcase}   # lambdas function

	generates_token_for :password_reset, expires_in: 5.minutes do
		password_salt&.last(10)
	end

	generates_token_for :email_confirmation, expires_in: 5.minutes do
		email
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    private

    def authenticate_teacher!
        redirect_to root_path, alert: "You must be logged in." unless teacher_signed_in?
    end

    def current_teacher
        Current.teacher ||= authenticate_teacher_from_session    
    end
    helper_method :current_teacher

    def authenticate_teacher_from_session
        Teacher.find_by(id: session[:teacher_id])
    end

    def teacher_signed_in?
        current_teacher.present?
    end
    helper_method :teacher_signed_in?

    def login(teacher)   #login method 
        Current.teacher = teacher
        reset_session
        session[:teacher_id] = teacher.id
    end

    def logout(teacher)  #logout method
        Current.teacher = nil
        reset_session
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@students = Student.all.page(params[:page]).per(10) 
	end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

	before_action :set_teacher_by_token, only: [:edit, :update]

	def new
	end

	def create
		if (teacher = Teacher.find_by(email: params[:email]))
			PasswordMailer.with(
				teacher: teacher,
				token: teacher.generate_token_for(:password_reset)
			).password_reset.deliver_later
		end
		redirect_to root_path, notice: "Check email to reset your password"
	end

	def edit
	end

	def update
		if @teacher.update(password_params)
			redirect_to new_session_path, notice: "Your password reset successfully now you can login"
		else
			render :edit, status: :unprocessable_entity
		end
	end

	private

	def set_teacher_by_token
		@teacher = Teacher.find_by_token_for(:password_reset, params[:token])
		redirect_to new_password_reset_path alert: "Invalid Token" unless @teacher.present?
	end

	def password_params
		params.require(:teacher).permit(:password, :password_confirmation)
	end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
	before_action :authenticate_teacher!

	def edit
	end

	def update
		if current_teacher.update(password_params)
			redirect_to home_index_path, notice: "Your password updated successfully"
		else
			render :edit, status: :unprocessable_entity
		end
	end

	private

	def password_params
		params.require(:teacher).permit(:password, :password_confirmation, :password_challenge).with_defaults(password_challenge: "")
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
	def new
		@teacher = Teacher.new
	end

	def create
		@teacher = Teacher.new(registration_params)
		if @teacher.save
			login @teacher
			redirect_to home_index_path
		else
			render :new, status: :unprocessable_entity
		end
	end

	private

	def registration_params
		params.require(:teacher).permit(:name, :email, :password, :password_confirmation)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
	def new
	end

	def create
		if teacher = Teacher.authenticate_by(email: params[:email], password: params[:password])
			login teacher
			redirect_to home_index_path, notice: "You are Signed in Successfully."
		else
			flash[:alert] = "Invalid email or password"
			render :new, status: :unprocessable_entity
		end
	end

	def destroy
		logout current_teacher
		redirect_to root_path, notice: "Successfully logged out."
	end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    before_action :authenticate_teacher!
    before_action :set_id, only: %i[edit update destroy]
    
    def new
        @student = Student.new
    end

    def create
        @student = Student.find_or_initialize_by(name: params[:student][:name], subject: params[:student][:subject])
        @student.marks = params[:student][:marks].to_i  # This will replace the old marks with the new marks
        if @student.save
            redirect_to home_index_path, notice: 'Student create sccessfully'
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @student.update(student_params)
            redirect_to home_index_path, notice: 'Student updated successfully'
        else
            render :edit
        end
    end

    def destroy
        @student.destroy
        redirect_to home_index_path, notice: 'Student deleted successfully'
    end

    private
    def set_id
        @student = Student.find(params[:id])
    end

    def student_params
        params.require(:student).permit(:name, :subject, :marks)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/home/index.html.erb
<table class="student-table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Subject</th>
            <th>Mark</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <% @students.each do |student| %>
        <tr>
            <td>
                <div class="student-name">
                    <div class="circle-icon"><%= student.name.first.upcase %></div>
                    <%= student.name.capitalize %>
                </div>
            </td>
            <td><%= student.subject.capitalize %></td>
            <td><%= student.marks %></td>
            <td>
                <div class="dropdown">
                    <button class="dropbtn">&#9660;</button>
                    <div id="myDropdown-<%= student.id %>" class="dropdown-content">
                        <%= link_to 'Edit', edit_student_path(student), class: "dropdown-item" %>
                        <%= link_to "Delete", student_path(student), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "dropdown-item" %>
                    </div>
                </div>
            </td>      
        </tr>
        <% end %>
    </tbody>
</table>

<% if current_teacher %>
    <div class="add-btn-container">
        <%= link_to 'Add New Student', new_student_path, class: "btn btn-primary" %>
    </div>
    <div class="teacher-email">
        User: <%= current_teacher.email %>
    </div>
<% end %>
<%= paginate @students %>

<script>
    function toggleDropdown(studentId) {
        var dropdown = document.getElementById("myDropdown-" + studentId);
        dropdown.classList.toggle("show");
    }

    // Close the dropdown if the user clicks outside of it
    window.onclick = function(event) {
        if (!event.target.matches('.dropdown button')) {
            var dropdowns = document.getElementsByClassName("dropdown-content");
            for (var i = 0; i < dropdowns.length; i++) {
                var openDropdown = dropdowns[i];
                if (openDropdown.classList.contains('show')) {
                    openDropdown.classList.remove('show');
                }
            }
        }
    }
</script>

app/views/layouts/_header.html.erb
<header>
    <div class="logo">
        <a>TeacherPortal</a>
    </div>
    <nav>
        <ul>
            <li><%= link_to "Home", home_index_path %></li>
            <% if teacher_signed_in? %>
                <li><%= link_to "Edit Password", edit_password_path %></li>
                <li><%= button_to "Log out", session_path, method: :delete %></li>
            <% else %>
                <% unless controller_name == 'sessions' && action_name == 'new' %>
                    <li><%= link_to "Log-in", new_session_path %></li>
                <% end %>
                <% unless controller_name == 'registrations' && action_name == 'new' %>
                    <li><%= link_to "Sign-up", new_registration_path %></li>
                <% end %>
            <% end %>
        </ul>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Teacher Portal" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'styles', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'pagination', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'dropdown', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_importmap_tags %>

    <style>
      .flash {
        padding: 15px;
        margin: 15px 0;
        border-radius: 8px;
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        animation: fadeIn 0.5s;
        transition: opacity 0.5s ease;
      }

      .flash.notice {
        background-color: #d4edda;
        color: #155724;
        border-left: 5px solid #c3e6cb;
      }

      .flash.alert {
        background-color: #f8d7da;
        color: #721c24;
        border-left: 5px solid #f5c6cb;
      }

      /* Fade-in animation */
      @keyframes fadeIn {
        from { opacity: 0; }
        to { opacity: 1; }
      }

    </style>
  </head>

  <body>

    <% flash.each do |key, message| %>
      <div class="flash <%= key %>"><%= message %></div>
    <% end %>

    <%= render "layouts/header"%>
    <%= yield %>
  </body>
</html>

app/views/password_resets/edit.html.erb
<div class="login-body">
	<div class="login-container">
		<div class="login-box">
			<div class="login-logo">Reset Password</div>
			<%= form_with model: @teacher, url: password_reset_path(token: params[:token]), class: "login-form" do |form| %>
				<% if form.object.errors.any? %>
					<% form.object.errors.full_messages.each do |message| %>
						<div><%= message %></div>
					<% end %>
				<% end %>
	
				<div class="form-group">
					<%= form.label :password, class: "form-label" %>
					<%= form.password_field :password, class: "form-control", placeholder: "Enter your password", required: true %>
				</div>

				<div class="form-group">
					<%= form.label :password_confirmation,"Confirm Password", class: "form-label" %>
					<%= form.password_field :password_confirmation, class: "form-control", placeholder: "Enter your Confirm password", required: true %>
				</div>

				<div class="form-group">
					<%= form.submit "Reset Password", class: "login-btn btn btn-primary" %>
				</div>
			<% end %>
			<%= link_to 'Back', root_path %>
  		</div>	
  	</div>
</div>

app/views/password_resets/new.html.erb
<div class="login-body">
    <div class="login-container">
        <div class="login-box">
            <div class="login-logo">Reset Password</div>
			<%= form_with model: @teacher, url: password_reset_path, class: "login-form" do |form| %>
				<div class="form-group">
					<%= form.label :email, class: "form-label" %>
					<%= form.email_field :email, class: "form-control", placeholder: "Enter your email", required: true %>
				</div>		

				<div>
					<%= form.submit "Reset Password", class: "login-btn btn btn-primary"%>
				</div>
			<% end %>
    	</div>
    </div>
</div>

app/views/students/edit.html.erb
<div class="login-body">
    <div class="login-container">
        <div class="login-box">
            <div class="logo">Edit Student</div>

            <%= form_with model: @student, local: true, class: "login-form" do |form| %>
              <div class="form-group">
                <%= form.label :name, class: "form-label" %>
                <%= form.text_field :name, class: "form-control", placeholder: "Enter your name", required: true %>
              </div>

              <div class="form-group">
                <%= form.label :subject, class: "form-label" %>
                <%= form.text_field :subject, class: "form-control", placeholder: "Enter your subject", required: true %>
              </div>

              <div class="form-group">
                <%= form.label :marks, class: "form-label" %>
                <%= form.number_field :marks, class: "form-control", placeholder: "Enter your marks", required: true %>
              </div>

              <div class="form-group">
                <%= form.submit 'Update Student', class: "login-btn btn btn-primary" %>
              </div>
            <% end %>
            <%= link_to 'Back', home_index_path %>
        </div>
    </div>
</div>

app/views/students/new.html.erb
<div class="login-body">
    <div class="login-container">
        <div class="login-box">
            <div class="logo">Add Student</div>

            <%= form_with model: @student, local: true, class: "login-form" do |form| %>
              <div class="form-group">
                <%= form.label :name, class: "form-label" %>
                <%= form.text_field :name, class: "form-control", placeholder: "Enter your name", required: true %>
              </div>

              <div class="form-group">
                <%= form.label :subject, class: "form-label" %>
                <%= form.text_field :subject, class: "form-control", placeholder: "Enter your subject", required: true %>
              </div>

              <div class="form-group">
                <%= form.label :marks, class: "form-label" %>
                <%= form.number_field :marks, class: "form-control", placeholder: "Enter your marks", required: true %>
              </div>

              <div class="form-group">
                <%= form.submit 'Add Student', class: "login-btn btn btn-primary" %>
              </div>
            <% end %>
            <%= link_to 'Back', home_index_path %>
        </div>
    </div>
</div>